server:
  port: 9000
  servlet:
    context-path: /auth-server
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
